// `bun smoke`'s AUTHORIZED PREPARATION and PREFLIGHT, one step per run of this
// process — the database half of the boot (smoke-production-spec.md §7: "config
// validation → plan and deployment lock → database create/restore (local) →
// target lock (§2) → identity matrix (§4.3) → authorized preparation →
// preflight → containers").
//
// WHO RUNS IT. scripts/lib/smoke-main.ts, from the HOST, never from inside an
// application container: `bun --no-env-file backend/scripts/smoke-prepare.ts`
// with one JSON request in RM_PREPARE_REQUEST (no secret in it) and stdio
// inherited, so a remote run's rm_owner prompt reaches the operator's terminal.
// The result is written to the request's `resultFile`. A separate process
// rather than an import, because every module below validates the environment
// at import (backend/src/config.ts requires DATABASE_URL) and the smoke must
// not publish a database credential into its own environment, where every
// child it starts would inherit it (issue #456).
//
// THE LOCK IS THE PARENT'S. The smoke holds the §2 session target lock on its
// own dedicated connection for the whole run and acquires it before anything
// here runs; this process must not take it again (it would wait on its own
// parent). It is handed the parent's lock backend pid, and every step proves
// through `observeTargetLock` that the parent still holds it before it writes.
// Every write then runs inside the mutation fence on the connection performing
// it (`withMutationFence`, `withFenceOn`), so a competitor that wins the session
// lock after the parent's connection died still waits for the write to end.
//
// THE STEPS, each rm_owner, each fenced:
//   bootstrap  `--local blank`: the snapshot's declaration, bootstrap data,
//              grants, baselined ledger, manifest and `deployment_identity =
//              rehearsal` (bootstrapBlankDatabase, §5, §8.1). The local
//              superuser has already created the four roles and the database
//              and nothing else (§7.3); it is not used here.
//   enroll     `--local dump`: the restored copy's enrollment overwritten with
//              `rehearsal` through rm_owner (enrollAsRehearsal, §4.2), before
//              any stage tool connects to it. A copy with NO table — a
//              production dump that predates 0063 — takes the identity-first
//              pass instead (localDumpIdentityFirst, D55 (9), (10)): 0063 and
//              `rehearsal` in one fenced transaction, only on the container
//              this run restored, only over loopback, never under
//              RM_ENV=prod, only from the production baseline ledger.
//   migrate    `--migrate`: migrateCommand as the `smoke_flag` caller — gates,
//              owner password (smoke's generated one locally, typed on a
//              remote rehearsal), an explicit `y` on a remote, the run, a
//              receipt in the instance's state directory (§8.5).
//   seed       `--seed`: the rehearsal and populated-database gate and the demo
//              seed, in ONE fenced transaction (seed.ts seedDemo, §5).
//   preflight  runPreflight("full"), checks 1-6, read-only, against a
//              top-level `rm_readonly` pool, with the api's registry loaded as
//              check 2's input (§7, §7.1). The report goes to the result file
//              and the boot refuses on any refusal.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import postgres from "postgres";
import { loadEnvFile, urlForRole } from "../../scripts/lib/env-role.ts";
import { readJournal } from "../../scripts/lib/smoke-journal.ts";
import { instancePaths, readRolePasswords, readStackState } from "../../scripts/lib/smoke-state.ts";
import { smokeTwinUrlFromContainer } from "../../scripts/lib/smoke-twin.ts";
import type { LockHolder } from "../src/db/target-lock.ts";

/** Everything one step needs, and no secret: passwords are read from the files it names. */
export interface PrepareRequest {
  readonly action: "bootstrap" | "enroll" | "migrate" | "seed" | "preflight";
  /** The §4.1 policy the boot resolved; `null` when RM_ENV is unset. */
  readonly rmEnv: "prod" | "stage" | null;
  readonly connection: "remote" | "local";
  /** How the host reaches the target. */
  readonly target: { readonly host: string; readonly port: number; readonly database: string; readonly sslmode: string };
  /**
   * Where the role passwords are. `instance`: the instance's
   * role-passwords.json (§5 — all four, the owner's included, generated by
   * smoke for a Postgres it owns). `home-env`: `~/.env` (§3 — the three
   * runtime roles; rm_owner is never there and is typed instead).
   */
  readonly credentials:
    | { readonly source: "instance"; readonly stateRoot: string; readonly instance: string }
    | { readonly source: "home-env"; readonly file: string };
  /** The parent's session target lock: its backend pid and the holder it published. */
  readonly lock: { readonly backendPid: number; readonly holder: LockHolder };
  /** The instance's state directory, where a migrate receipt goes. */
  readonly stateDir: string;
  readonly resultFile: string;
  readonly nonInteractive: boolean;
  /** `enroll`: what the enrollment row's note records (which dump was restored). */
  readonly note?: string;
}

/** The result file's shape. */
export type PrepareResult =
  | { readonly ok: true; readonly action: PrepareRequest["action"]; readonly detail: Record<string, unknown> }
  | { readonly ok: false; readonly action: PrepareRequest["action"]; readonly error: string };

const RUNTIME_ROLES = ["rm_app", "rm_worker", "rm_readonly"] as const;

/** A URL for `role` on the request's target, or undefined when no password for it is available. */
function urlFor(request: PrepareRequest, role: string): string | undefined {
  const passwords: Record<string, string | undefined> = (() => {
    if (request.credentials.source === "instance") {
      return { ...readRolePasswords(instancePaths(request.credentials.stateRoot, request.credentials.instance)) };
    }
    const env = loadEnvFile(request.credentials.file) ?? {};
    return Object.fromEntries(RUNTIME_ROLES.map((r) => [r, env[r]]));
  })();
  const password = passwords[role];
  if (password === undefined || password === "") return undefined;
  return urlForRole(
    {
      host: request.target.host,
      port: String(request.target.port),
      database: request.target.database,
      sslmode: request.target.sslmode,
      [role]: password,
    },
    role,
  );
}

function required(url: string | undefined, role: string): string {
  if (url === undefined) throw new Error(`no ${role} password is available for this target`);
  return url;
}

async function main(): Promise<PrepareResult> {
  const request = JSON.parse(process.env.RM_PREPARE_REQUEST ?? "null") as PrepareRequest | null;
  if (request === null) throw new Error("RM_PREPARE_REQUEST is not set; this process is started by `bun smoke`");
  const readerUrl = required(urlFor(request, "rm_readonly"), "rm_readonly");

  // backend/src/config.ts validates at IMPORT: DATABASE_URL is the runtime
  // role that can do no DDL, and RM_ENV the policy this boot runs under. The
  // owner credential never goes into the environment.
  process.env.DATABASE_URL = readerUrl;
  process.env.WORKER_DATABASE_URL = readerUrl;
  process.env.RM_ENV = request.rmEnv ?? "stage";

  const { assertStillHeld, observeTargetLock, withMutationFence } = await import("../src/db/target-lock.ts");
  const reader = postgres(readerUrl, { max: 1, onnotice: () => {} });
  const lock = observeTargetLock(reader, request.lock.backendPid, request.lock.holder);
  const done = (detail: Record<string, unknown>): PrepareResult => ({ ok: true, action: request.action, detail });
  try {
    await assertStillHeld(lock, `prepare ${request.action}`);

    switch (request.action) {
      case "bootstrap": {
        const { bootstrapBlankDatabase, loadSnapshot } = await import("../src/db/schema-snapshot.ts");
        const snapshot = await loadSnapshot();
        const result = await withMutationFence(
          { databaseUrl: required(urlFor(request, "rm_owner"), "rm_owner"), label: "bootstrap" },
          (tx) => bootstrapBlankDatabase(tx, snapshot),
        );
        return done({ baselined: result.baselined.length, manifest: result.manifest.contentHash });
      }

      case "enroll": {
        const { enrollAsRehearsal, isLoopbackHost, transactionIdentityStore } = await import("../../scripts/lib/smoke-identity.ts");
        const remote = request.connection !== "local" || !isLoopbackHost(request.target.host);
        // A dump restored from a database that predates 0063 has no table to
        // write `rehearsal` into: that is the `--local dump` identity-first
        // pass (D55 (9), (10)), and it proves its own guards first.
        const { identityTableExists } = await import("./migrate-run.ts");
        if (!(await identityTableExists(reader))) {
          const pass = await localDumpIdentityFirst(request, reader, lock, remote);
          return done({ kind: pass.row.kind, writtenBy: pass.row.writtenBy, identityFirst: pass.preIdentity.release });
        }
        const row = await withMutationFence(
          { databaseUrl: required(urlFor(request, "rm_owner"), "rm_owner"), label: "identity" },
          (tx) => enrollAsRehearsal(transactionIdentityStore(tx, { remote }), { note: request.note ?? null, remoteAcknowledged: false }),
        );
        return done({ kind: row.kind, writtenBy: row.writtenBy });
      }

      case "migrate": {
        const { migrateCommand, migrateReceiptPath } = await import("./migrate-run.ts");
        const { result, receipt } = await migrateCommand({
          caller: "smoke_flag",
          env: request.rmEnv,
          connection: request.connection,
          readerUrl,
          nonInteractive: request.nonInteractive,
          localOwnerPassword: request.connection === "local" ? ownerPassword(request) : undefined,
          lock: { heldByParent: () => lock },
          receiptPath: migrateReceiptPath(request.stateDir, new Date()),
          log: (m) => console.log(`[smoke:migrate] ${m}`),
        });
        return done({
          applied: result.applied,
          resumedAndVerified: result.resumedAndVerified,
          grantsRepaired: result.grantsRepaired,
          manifest: result.manifest.contentHash,
          baselined: result.baselined,
          receipt,
        });
      }

      case "seed": {
        const { confirmRemoteTarget, promptOwnerPassword, redactedTarget, urlAsRole } = await import("./migrate-run.ts");
        const { assertSeedable, seedDemo } = await import("../src/db/seed.ts");
        const gate = { caller: "smoke_flag" as const, env: request.rmEnv, connection: request.connection };
        // GATES BEFORE THE PASSWORD, as the migrate path holds them: the
        // rehearsal-only gate and the populated-database check run first,
        // read-only, over the rm_readonly reader while the boot holds the lock,
        // so a seed that will be refused never asks for rm_owner or a y. They
        // run again inside the fence (seedDemo), where they decide.
        await assertSeedable(reader, { rmEnv: request.rmEnv ?? undefined, explicitlyRequested: true });
        const password = await promptOwnerPassword(
          { ...gate, nonInteractive: request.nonInteractive, localOwnerPassword: request.connection === "local" ? ownerPassword(request) : undefined },
          readerUrl,
        );
        await confirmRemoteTarget({ connection: request.connection, nonInteractive: request.nonInteractive }, redactedTarget(readerUrl));
        await assertStillHeld(lock, "prepare seed");
        await withMutationFence({ databaseUrl: urlAsRole(readerUrl, "rm_owner", password), label: "seed" }, (tx) =>
          seedDemo(tx, { rmEnv: request.rmEnv ?? undefined }),
        );
        return done({});
      }

      case "preflight": {
        // Check 2's input is the registry of the programs this boot will run
        // (§7.1). The api's module graph is imported — its registrations
        // without its `Bun.serve` — together with the pipeline worker's
        // handlers, so the check judges the roles against what the containers
        // will actually issue.
        await importRegistrations();
        const { runPreflight, homeEnvPath, preflightReportLines } = await import("../src/db/preflight.ts");
        const { loadSnapshot } = await import("../src/db/schema-snapshot.ts");
        const tokens = new Map<(typeof RUNTIME_ROLES)[number], string>();
        for (const role of RUNTIME_ROLES) {
          const url = urlFor(request, role);
          if (url !== undefined) tokens.set(role, decodeURIComponent(new URL(url).password));
        }
        // A top-level pool, never a transaction or a reserved connection:
        // check 1 reads the server's address from the pool's own options.
        const pool = postgres(readerUrl, { max: 1, onnotice: () => {} });
        try {
          const report = await runPreflight(
            pool,
            {
              env: request.rmEnv,
              connection: request.connection,
              roles: [...RUNTIME_ROLES],
              codeFilenames: (await loadSnapshot()).filenames,
              envFilePath: homeEnvPath(),
            },
            "full",
            tokens,
          );
          for (const line of preflightReportLines(report)) console.log(line);
          return done({ report });
        } finally {
          await pool.end({ timeout: 5 });
        }
      }
    }
  } finally {
    await reader.end({ timeout: 5 }).catch(() => undefined);
  }
}

/**
 * The `--local dump` identity-first pass — the second of §4.3's three named
 * exceptions (D55 (9), (10)): a restored production dump that predates 0063
 * has no `deployment_identity` table, so the enrollment §4.2 requires has
 * nowhere to land. When the restored ledger equals the production baseline,
 * this applies 0063 and writes `rehearsal` in ONE fenced transaction as
 * rm_owner (migrate-run.ts applyIdentityFirst), before any other pending
 * migration; `--migrate` then takes the normal path, which accepts the state
 * the pass leaves.
 *
 * Its guards, each checked here for itself, in this order, before anything is
 * written — and none of them relaxable by any input:
 *   1. NEVER REMOTE. A remote connection refuses whatever RM_ENV, password or
 *      acknowledgement says: the request's connection must be local, its
 *      target a loopback address, and its owner password the one smoke
 *      generated for the instance (§5). The identity write itself refuses a
 *      remote store too (enrollAsRehearsal), so the rule holds twice.
 *   2. NOT PROD. `RM_ENV=prod` refuses (§4.3: prod never runs on a database
 *      smoke owns; enrollAsRehearsal refuses it again).
 *   3. THE COPY THIS RUN RESTORED. The instance's stack record names the
 *      restored container; this plan's open journal has its `restore`
 *      preparation committed; and the address the request connects to is the
 *      one Docker published for that container. A loopback port is bound by
 *      one listener, so a connection there reaches that container and no
 *      other database.
 *   4. THE BASELINE. The restored ledger equals one SUPPORTED_RELEASES
 *      baseline exactly (D55 (8)). A dump with any other pre-identity ledger
 *      refuses, naming how it differs.
 * The pass re-reads the baseline under its own fence and refuses if it moved.
 */
async function localDumpIdentityFirst(
  request: PrepareRequest,
  reader: postgres.Sql<{}>,
  lock: import("../src/db/target-lock.ts").HeldTargetLock,
  remote: boolean,
): Promise<import("./migrate-run.ts").IdentityFirstResult> {
  const refuse = (why: string): never => {
    throw new Error(
      `Refusing the --local dump identity-first pass (spec §4.3, D55 (9), (10)): ${why} Nothing was applied and no ` +
        "identity row was written.",
    );
  };
  if (remote || request.credentials.source !== "instance") {
    refuse(
      `its connection is remote (${request.target.host}:${request.target.port}, ${request.connection}). The pass runs ` +
        "only on the Postgres container this smoke run restored, over loopback, with the owner password smoke " +
        "generated; a remote connection refuses whatever RM_ENV, password or acknowledgement says.",
    );
  }
  if (request.rmEnv === "prod") refuse("RM_ENV=prod. The pass writes `rehearsal` and never runs under production policy.");
  proveRestoredByThisPlan(request, refuse);

  const { applyIdentityFirst, describeUnmatchedPreIdentity, readPreIdentityLedger } = await import("./migrate-run.ts");
  const state = await readPreIdentityLedger(reader);
  if (state === null) {
    refuse(`the restored copy has no deployment_identity table, and ${await describeUnmatchedPreIdentity(reader)}.`);
  }
  const { assertStillHeld } = await import("../src/db/target-lock.ts");
  await assertStillHeld(lock, "prepare enroll (identity-first)");
  const owner = postgres(required(urlFor(request, "rm_owner"), "rm_owner"), { max: 1, onnotice: () => {} });
  try {
    return await applyIdentityFirst(owner, {
      kind: "rehearsal",
      rmEnv: request.rmEnv,
      remote,
      expected: state!,
      note: `${request.note ?? "--local dump"}: identity-first from ${state!.release} (spec §4.3, D55 (10))`,
    });
  } finally {
    await owner.end({ timeout: 5 }).catch(() => undefined);
  }
}

/**
 * Guard 3 of the `--local dump` pass: the request's target is the container
 * this plan restored. Reads what the smoke parent recorded — the stack record's
 * `smokeTwinContainer` and this plan's journal — and asks Docker where that
 * container's Postgres is published.
 */
function proveRestoredByThisPlan(request: PrepareRequest, refuse: (why: string) => never): void {
  if (request.credentials.source !== "instance") refuse("it has no instance whose restore it could check.");
  const paths = instancePaths(request.credentials.stateRoot, request.credentials.instance);
  const container = readStackState(paths)?.smokeTwinContainer;
  if (!container) refuse(`instance ${request.credentials.instance} records no restored container.`);
  const journal = readJournal(paths);
  const planId = request.lock.holder.planId;
  if (journal === null || journal.closedAt !== null || planId === null || journal.planId !== planId) {
    refuse(`the open journal of instance ${request.credentials.instance} is not the journal of plan ${planId ?? "(none)"} that holds the target lock.`);
  }
  if (!journal!.phases.some((p) => p.phase === "prepare" && p.step === "restore" && p.status === "committed")) {
    refuse(`plan ${planId} has not committed a restore, so there is no copy this run restored.`);
  }
  const published = smokeTwinUrlFromContainer(container!);
  if (published === null) refuse(`the restored container ${container} is not running.`);
  const url = new URL(published!);
  if (url.hostname !== request.target.host || Number(url.port) !== request.target.port) {
    refuse(
      `the connection is ${request.target.host}:${request.target.port}, and the container this plan restored ` +
        `(${container}) is published at ${url.hostname}:${url.port}.`,
    );
  }
}

/** The generated owner password of a smoke-owned Postgres (§5). */
function ownerPassword(request: PrepareRequest): string {
  if (request.credentials.source !== "instance") throw new Error("the owner password is generated only for a Postgres smoke owns");
  return readRolePasswords(instancePaths(request.credentials.stateRoot, request.credentials.instance)).rm_owner;
}

/** Import every relative module the api entry imports, and the worker's handlers. */
async function importRegistrations(): Promise<void> {
  const { readFileSync } = await import("node:fs");
  const { dirname } = await import("node:path");
  const apiEntry = join(import.meta.dir, "..", "src", "api", "index.ts");
  const text = readFileSync(apiEntry, "utf8");
  const specifiers = [...text.matchAll(/^import\s[^;]*?\sfrom\s+"(\.{1,2}\/[^"]+)";/gm)].map((m) => m[1]!);
  for (const specifier of specifiers) await import(join(dirname(apiEntry), specifier));
  await import(join(import.meta.dir, "..", "src", "worker", "handlers", "index.ts"));
}

if (import.meta.main) {
  // A terminal's Ctrl-C reaches the whole foreground process group, this step
  // included. The boot records it and stops at its next phase boundary (§1.4);
  // this step must not die of it halfway through a fenced write. (The masked
  // owner prompt reads Ctrl-C as a key in raw mode and aborts the prompt itself.)
  process.on("SIGINT", () => {});
  const request = JSON.parse(process.env.RM_PREPARE_REQUEST ?? "null") as PrepareRequest | null;
  let result: PrepareResult;
  try {
    result = await main();
  } catch (error) {
    result = { ok: false, action: request?.action ?? "preflight", error: error instanceof Error ? error.message : String(error) };
    console.error(`[smoke:prepare] ${request?.action ?? "?"}: ${result.error}`);
  }
  if (request?.resultFile) writeFileSync(request.resultFile, `${JSON.stringify(result)}\n`, { mode: 0o600 });
  // An api module may start a timer at import; the result is out, so leave.
  process.exit(result.ok ? 0 : 1);
}

