// `bun smoke`'s AUTHORIZED PREPARATION and PREFLIGHT, one step per run of this
// process — the database half of the boot (smoke-production-spec.md §7: "config
// validation → plan and deployment lock → database create/restore (local) →
// target lock (§2) → identity matrix (§4.3) → authorized preparation →
// preflight → containers").
//
// WHO RUNS IT. scripts/lib/smoke-main.ts, from the HOST, never from inside an
// application container: `bun --no-env-file backend/scripts/smoke-prepare.ts`
// with one JSON request in RM_PREPARE_REQUEST (no secret in it) and stdio
// inherited, so a remote run's rm_owner prompt reaches the operator's terminal.
// The result is written to the request's `resultFile`. A separate process
// rather than an import, because every module below validates the environment
// at import (backend/src/config.ts requires DATABASE_URL) and the smoke must
// not publish a database credential into its own environment, where every
// child it starts would inherit it (issue #456).
//
// THE LOCK IS THE PARENT'S. The smoke holds the §2 session target lock on its
// own dedicated connection for the whole run and acquires it before anything
// here runs; this process must not take it again (it would wait on its own
// parent). It is handed the parent's lock backend pid, and every step proves
// through `observeTargetLock` that the parent still holds it before it writes.
// Every write then runs inside the mutation fence on the connection performing
// it (`withMutationFence`, `withFenceOn`), so a competitor that wins the session
// lock after the parent's connection died still waits for the write to end.
//
// THE STEPS, each rm_owner, each fenced:
//   bootstrap  `--local blank`: the snapshot's declaration, bootstrap data,
//              grants, baselined ledger, manifest and `deployment_identity =
//              rehearsal` (bootstrapBlankDatabase, §5, §8.1). The local
//              superuser has already created the four roles and the database
//              and nothing else (§7.3); it is not used here.
//   enroll     `--local dump`: the restored copy's enrollment overwritten with
//              `rehearsal` through rm_owner (enrollAsRehearsal, §4.2), before
//              any stage tool connects to it.
//   migrate    `--migrate`: migrateCommand as the `smoke_flag` caller — gates,
//              owner password (smoke's generated one locally, typed on a
//              remote rehearsal), an explicit `y` on a remote, the run, a
//              receipt in the instance's state directory (§8.5).
//   seed       `--seed`: the rehearsal and populated-database gate and the demo
//              seed, in ONE fenced transaction (seed.ts seedDemo, §5).
//   preflight  runPreflight("full"), checks 1-6, read-only, against a
//              top-level `rm_readonly` pool, with the api's registry loaded as
//              check 2's input (§7, §7.1). The report goes to the result file
//              and the boot refuses on any refusal.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import postgres from "postgres";
import { loadEnvFile, urlForRole } from "../../scripts/lib/env-role.ts";
import { instancePaths, readRolePasswords } from "../../scripts/lib/smoke-state.ts";
import type { LockHolder } from "../src/db/target-lock.ts";

/** Everything one step needs, and no secret: passwords are read from the files it names. */
export interface PrepareRequest {
  readonly action: "bootstrap" | "enroll" | "migrate" | "seed" | "preflight";
  /** The §4.1 policy the boot resolved; `null` when RM_ENV is unset. */
  readonly rmEnv: "prod" | "stage" | null;
  readonly connection: "remote" | "local";
  /** How the host reaches the target. */
  readonly target: { readonly host: string; readonly port: number; readonly database: string; readonly sslmode: string };
  /**
   * Where the role passwords are. `instance`: the instance's
   * role-passwords.json (§5 — all four, the owner's included, generated by
   * smoke for a Postgres it owns). `home-env`: `~/.env` (§3 — the three
   * runtime roles; rm_owner is never there and is typed instead).
   */
  readonly credentials:
    | { readonly source: "instance"; readonly stateRoot: string; readonly instance: string }
    | { readonly source: "home-env"; readonly file: string };
  /** The parent's session target lock: its backend pid and the holder it published. */
  readonly lock: { readonly backendPid: number; readonly holder: LockHolder };
  /** The instance's state directory, where a migrate receipt goes. */
  readonly stateDir: string;
  readonly resultFile: string;
  readonly nonInteractive: boolean;
  /** `enroll`: what the enrollment row's note records (which dump was restored). */
  readonly note?: string;
}

/** The result file's shape. */
export type PrepareResult =
  | { readonly ok: true; readonly action: PrepareRequest["action"]; readonly detail: Record<string, unknown> }
  | { readonly ok: false; readonly action: PrepareRequest["action"]; readonly error: string };

const RUNTIME_ROLES = ["rm_app", "rm_worker", "rm_readonly"] as const;

/** A URL for `role` on the request's target, or undefined when no password for it is available. */
function urlFor(request: PrepareRequest, role: string): string | undefined {
  const passwords: Record<string, string | undefined> = (() => {
    if (request.credentials.source === "instance") {
      return { ...readRolePasswords(instancePaths(request.credentials.stateRoot, request.credentials.instance)) };
    }
    const env = loadEnvFile(request.credentials.file) ?? {};
    return Object.fromEntries(RUNTIME_ROLES.map((r) => [r, env[r]]));
  })();
  const password = passwords[role];
  if (password === undefined || password === "") return undefined;
  return urlForRole(
    {
      host: request.target.host,
      port: String(request.target.port),
      database: request.target.database,
      sslmode: request.target.sslmode,
      [role]: password,
    },
    role,
  );
}

function required(url: string | undefined, role: string): string {
  if (url === undefined) throw new Error(`no ${role} password is available for this target`);
  return url;
}

async function main(): Promise<PrepareResult> {
  const request = JSON.parse(process.env.RM_PREPARE_REQUEST ?? "null") as PrepareRequest | null;
  if (request === null) throw new Error("RM_PREPARE_REQUEST is not set; this process is started by `bun smoke`");
  const readerUrl = required(urlFor(request, "rm_readonly"), "rm_readonly");

  // backend/src/config.ts validates at IMPORT: DATABASE_URL is the runtime
  // role that can do no DDL, and RM_ENV the policy this boot runs under. The
  // owner credential never goes into the environment.
  process.env.DATABASE_URL = readerUrl;
  process.env.WORKER_DATABASE_URL = readerUrl;
  process.env.RM_ENV = request.rmEnv ?? "stage";

  const { assertStillHeld, observeTargetLock, withMutationFence } = await import("../src/db/target-lock.ts");
  const reader = postgres(readerUrl, { max: 1, onnotice: () => {} });
  const lock = observeTargetLock(reader, request.lock.backendPid, request.lock.holder);
  const done = (detail: Record<string, unknown>): PrepareResult => ({ ok: true, action: request.action, detail });
  try {
    await assertStillHeld(lock, `prepare ${request.action}`);

    switch (request.action) {
      case "bootstrap": {
        const { bootstrapBlankDatabase, loadSnapshot } = await import("../src/db/schema-snapshot.ts");
        const snapshot = await loadSnapshot();
        const result = await withMutationFence(
          { databaseUrl: required(urlFor(request, "rm_owner"), "rm_owner"), label: "bootstrap" },
          (tx) => bootstrapBlankDatabase(tx, snapshot),
        );
        return done({ baselined: result.baselined.length, manifest: result.manifest.contentHash });
      }

      case "enroll": {
        const { enrollAsRehearsal, transactionIdentityStore } = await import("../../scripts/lib/smoke-identity.ts");
        const row = await withMutationFence(
          { databaseUrl: required(urlFor(request, "rm_owner"), "rm_owner"), label: "identity" },
          (tx) => enrollAsRehearsal(transactionIdentityStore(tx), { note: request.note ?? null, remoteAcknowledged: false }),
        );
        return done({ kind: row.kind, writtenBy: row.writtenBy });
      }

      case "migrate": {
        const { migrateCommand, migrateReceiptPath } = await import("./migrate-run.ts");
        const { result, receipt } = await migrateCommand({
          caller: "smoke_flag",
          env: request.rmEnv,
          connection: request.connection,
          readerUrl,
          nonInteractive: request.nonInteractive,
          localOwnerPassword: request.connection === "local" ? ownerPassword(request) : undefined,
          lock: { heldByParent: () => lock },
          receiptPath: migrateReceiptPath(request.stateDir, new Date()),
          log: (m) => console.log(`[smoke:migrate] ${m}`),
        });
        return done({
          applied: result.applied,
          resumedAndVerified: result.resumedAndVerified,
          grantsRepaired: result.grantsRepaired,
          manifest: result.manifest.contentHash,
          baselined: result.baselined,
          receipt,
        });
      }

      case "seed": {
        const { confirmRemoteTarget, promptOwnerPassword, redactedTarget, urlAsRole } = await import("./migrate-run.ts");
        const { seedDemo } = await import("../src/db/seed.ts");
        const gate = { caller: "smoke_flag" as const, env: request.rmEnv, connection: request.connection };
        const password = await promptOwnerPassword(
          { ...gate, nonInteractive: request.nonInteractive, localOwnerPassword: request.connection === "local" ? ownerPassword(request) : undefined },
          readerUrl,
        );
        await confirmRemoteTarget({ connection: request.connection, nonInteractive: request.nonInteractive }, redactedTarget(readerUrl));
        await assertStillHeld(lock, "prepare seed");
        await withMutationFence({ databaseUrl: urlAsRole(readerUrl, "rm_owner", password), label: "seed" }, (tx) =>
          seedDemo(tx, { rmEnv: request.rmEnv ?? undefined }),
        );
        return done({});
      }

      case "preflight": {
        // Check 2's input is the registry of the programs this boot will run
        // (§7.1). The api's module graph is imported — its registrations
        // without its `Bun.serve` — together with the pipeline worker's
        // handlers, so the check judges the roles against what the containers
        // will actually issue.
        await importRegistrations();
        const { runPreflight, homeEnvPath, preflightReportLines } = await import("../src/db/preflight.ts");
        const { loadSnapshot } = await import("../src/db/schema-snapshot.ts");
        const tokens = new Map<(typeof RUNTIME_ROLES)[number], string>();
        for (const role of RUNTIME_ROLES) {
          const url = urlFor(request, role);
          if (url !== undefined) tokens.set(role, decodeURIComponent(new URL(url).password));
        }
        // A top-level pool, never a transaction or a reserved connection:
        // check 1 reads the server's address from the pool's own options.
        const pool = postgres(readerUrl, { max: 1, onnotice: () => {} });
        try {
          const report = await runPreflight(
            pool,
            {
              env: request.rmEnv,
              connection: request.connection,
              roles: [...RUNTIME_ROLES],
              codeFilenames: (await loadSnapshot()).filenames,
              envFilePath: homeEnvPath(),
            },
            "full",
            tokens,
          );
          for (const line of preflightReportLines(report)) console.log(line);
          return done({ report });
        } finally {
          await pool.end({ timeout: 5 });
        }
      }
    }
  } finally {
    await reader.end({ timeout: 5 }).catch(() => undefined);
  }
}

/** The generated owner password of a smoke-owned Postgres (§5). */
function ownerPassword(request: PrepareRequest): string {
  if (request.credentials.source !== "instance") throw new Error("the owner password is generated only for a Postgres smoke owns");
  return readRolePasswords(instancePaths(request.credentials.stateRoot, request.credentials.instance)).rm_owner;
}

/** Import every relative module the api entry imports, and the worker's handlers. */
async function importRegistrations(): Promise<void> {
  const { readFileSync } = await import("node:fs");
  const { dirname } = await import("node:path");
  const apiEntry = join(import.meta.dir, "..", "src", "api", "index.ts");
  const text = readFileSync(apiEntry, "utf8");
  const specifiers = [...text.matchAll(/^import\s[^;]*?\sfrom\s+"(\.{1,2}\/[^"]+)";/gm)].map((m) => m[1]!);
  for (const specifier of specifiers) await import(join(dirname(apiEntry), specifier));
  await import(join(import.meta.dir, "..", "src", "worker", "handlers", "index.ts"));
}

if (import.meta.main) {
  const request = JSON.parse(process.env.RM_PREPARE_REQUEST ?? "null") as PrepareRequest | null;
  let result: PrepareResult;
  try {
    result = await main();
  } catch (error) {
    result = { ok: false, action: request?.action ?? "preflight", error: error instanceof Error ? error.message : String(error) };
    console.error(`[smoke:prepare] ${request?.action ?? "?"}: ${result.error}`);
  }
  if (request?.resultFile) writeFileSync(request.resultFile, `${JSON.stringify(result)}\n`, { mode: 0o600 });
  // An api module may start a timer at import; the result is out, so leave.
  process.exit(result.ok ? 0 : 1);
}

