// One-time historical backfill of v0 pre-launch Investment Committee content:
// the three swarm member personas (Athena, Robot Money, Woon), the four
// subjects they cover, every past session with its per-agent narrative
// "takes", and the subject snapshots and briefs those sessions were built on.
//
// SOURCE is the committed artifact in seed-data/, itself generated by
// scripts/v0-seed-regenerate.ts from robotmoney/v0-archive — a verbatim copy
// of what v0 published, collected from agentjuno/robotmoney. (The first pass
// of this script read an archive built from robotmoney-site, a fork 2015
// commits behind, and so imported 32 of 72 sessions and no snapshots or
// briefs at all.)
//
// Direct-SQL pattern (like src/db/seed.ts's backfillWalletHistory()), NOT the
// HTTP-API pattern of edgar-seed-bootstrap.ts: that pattern exists because
// EDGAR ingestion must flow through the live analytics gap-fill API, and
// there is no equivalent generic ingest endpoint for
// swarm_members/subjects/sessions. This is a one-time historical backfill,
// not live ingestion, so it talks to Postgres directly via db/client.ts.
//
// Processes in DEPENDENCY ORDER — members -> subjects -> sessions -> takes ->
// snapshots -> briefs (everything after subjects FKs to them) — and for every
// entity:
//   * natural key not found  -> INSERT (append-only: fills in what's missing)
//   * natural key found, content matches (every mapped column, not just a
//     hash) -> silent no-op
//   * natural key found, content differs -> NEVER overwrite. Log the entity,
//     natural key, and every differing field (old vs incoming), and count it
//     as an "inconsistency". Every entity is still attempted even after a
//     drift is found (so later genuinely-new rows still get inserted); the
//     script exits non-zero at the very end if any inconsistency was found.
//
// Sessions additionally get:
//   * swarm_recommendation = v0's `committee_recommendation` verbatim
//   * state = 'published', published_at = generated_at
//   * their takes written to swarm_recommendations — see the block above
//     processTake() for why they are signed here rather than stored in a
//     legacy column (0026 added one; 0027 drops it again).
//   * every take's member_id is checked against swarm_members — a missing
//     reference is WARNED about and skipped, never a crash.
//
// Fields v1 has no column for are dropped HERE, at the point of insert, never
// in the archive: take.model/usage, snapshot.fetched_at/source_type. The
// artifact keeps saying exactly what v0 said. Values v1 spells differently are
// rewritten under the same rule — see canonicalizeAvatar() for v0's
// pre-rename /avatars/committee/ path.
//
// Usage: DATABASE_URL=... bun run scripts/v0-seed-bootstrap.ts
// (V0_ARCHIVE_SIGNING_KEY overrides the published archival key; see
// src/swarm/v0-archive.ts for why that key is published rather than secret.)
// (wired as `bun run v0-seed:bootstrap` in package.json, and reached from the
// repo root via `bun run bootstrap` -> backend prod-bootstrap)
import { canonicalizeSubmission, signMessage } from "../src/lib/signing.ts";
import { sql, closeDb, jsonValue } from "../src/db/client.ts";
import {
  loadV0Archive,
  V0_ARCHIVE_NONCE_PREFIX,
  V0_ARCHIVE_SIGNING_KEY_PKCS8_B64,
  type V0Member,
  type V0Subject,
  type V0Session,
  type V0Take,
  type V0Snapshot,
  type V0Brief,
} from "../src/swarm/v0-archive.ts";

type FieldKind = "text" | "json" | "numeric" | "date" | "timestamp";

interface FieldSpec {
  column: string;
  kind: FieldKind;
  expected: unknown;
}

export interface Drift {
  entity: string;
  naturalKey: string;
  field: string;
  oldValue: unknown;
  newValue: unknown;
}

// Per-entity insert/unchanged/drift counts plus every field-level drift found,
// so a caller (the CLI entrypoint below, or a test) can act on precise
// structured data instead of scraping console output or a process-global exit
// code. Same shape convention as repopulateEdgarSeed()'s report
// (analytics/edgar-seed-loader.ts).
interface EntityCounts {
  inserted: number;
  unchanged: number;
  drifted: number;
  total: number;
}

export interface V0BootstrapResult {
  members: EntityCounts;
  subjects: EntityCounts;
  sessions: EntityCounts;
  takes: EntityCounts;
  snapshots: EntityCounts;
  briefs: EntityCounts;
  drifts: Drift[];
}

// Accumulator so each dataset's loop below is the same three lines rather than
// three near-identical counter triples per entity.
function tally(): EntityCounts & { record(o: RowOutcome): void } {
  const c = {
    inserted: 0,
    unchanged: 0,
    drifted: 0,
    total: 0,
    record(o: RowOutcome) {
      c.total++;
      if (o === "inserted") c.inserted++;
      else if (o === "unchanged") c.unchanged++;
      else c.drifted++;
    },
  };
  return c;
}

// Order/key-order-independent structural equality for parsed jsonb values.
// `undefined`-valued keys are treated as absent, matching how `JSON.parse`
// (never produces undefined) and Postgres's jsonb (drops nothing but also
// never carries an explicit "undefined") both behave.
function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (a == null || b == null) return a == null && b == null;
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b)) return false;
    if (a.length !== b.length) return false;
    return a.every((v, i) => deepEqual(v, b[i]));
  }
  if (typeof a === "object" && typeof b === "object") {
    const ao = a as Record<string, unknown>;
    const bo = b as Record<string, unknown>;
    const aKeys = Object.keys(ao).filter((k) => ao[k] !== undefined);
    const bKeys = Object.keys(bo).filter((k) => bo[k] !== undefined);
    if (aKeys.length !== bKeys.length) return false;
    return aKeys.every((k) => Object.prototype.hasOwnProperty.call(bo, k) && deepEqual(ao[k], bo[k]));
  }
  return false;
}

// Kind-aware equality between an incoming (archive) value and the value read
// back from Postgres. `numeric`/`date`/`timestamp` need normalization because
// postgres.js round-trips those types through string/Date representations
// that are not byte-identical to the archive's plain JS number/ISO string
// even when the underlying value is unchanged.
function fieldsEqual(kind: FieldKind, expected: unknown, actual: unknown): boolean {
  const e = expected ?? null;
  const act = actual ?? null;
  if (e === null || act === null) return e === act;
  switch (kind) {
    case "text":
      return e === act;
    case "json":
      return deepEqual(e, act);
    case "numeric":
      return Number(e) === Number(act);
    case "date": {
      const de = typeof e === "string" ? e.slice(0, 10) : new Date(e as string).toISOString().slice(0, 10);
      const da = typeof act === "string" ? act.slice(0, 10) : new Date(act as string).toISOString().slice(0, 10);
      return de === da;
    }
    case "timestamp":
      return new Date(e as string).toISOString() === new Date(act as string).toISOString();
  }
}

function diffRow(entity: string, naturalKey: string, fields: FieldSpec[], actualRow: Record<string, unknown>): Drift[] {
  const drifts: Drift[] = [];
  for (const f of fields) {
    const actual = actualRow[f.column];
    if (!fieldsEqual(f.kind, f.expected, actual)) {
      drifts.push({ entity, naturalKey, field: f.column, oldValue: actual, newValue: f.expected });
    }
  }
  return drifts;
}

type RowOutcome = "inserted" | "unchanged" | "drift";

// v0 published its member avatars under /avatars/committee/<id>.jpg. The
// canonical v1 path is /avatars/swarm/<id>.<ext> (docs/decisions.md D31): it
// is what every committed manifest under
// frontend/public/data/swarm/manifests/members/ says, what that directory's
// _SCHEMA.md specifies, and what src/swarm/roster-seed.ts's LIVE_ROSTER
// writes into the same jsonb `avatar` column for athena/robotmoney.
//
// The rewrite happens HERE, at the point of insert — exactly the rule the
// module header states for take.model/usage: v1's shape is applied by the
// importer, never by editing the artifact, so seed-data/ keeps saying
// verbatim what v0 said. Without it the two writers disagree on `.path` for
// the two members they share, and whichever runs second reports member drift
// and exits `bun run prod-bootstrap` non-zero (issue #540).
const V0_AVATAR_PREFIX = "/avatars/committee/";
const CANONICAL_AVATAR_PREFIX = "/avatars/swarm/";

export function canonicalizeAvatar(avatar: unknown): unknown {
  if (avatar === null || avatar === undefined) return null;
  if (typeof avatar !== "object" || Array.isArray(avatar)) return avatar;
  const path = (avatar as { path?: unknown }).path;
  if (typeof path !== "string" || !path.startsWith(V0_AVATAR_PREFIX)) return avatar;
  return { ...(avatar as Record<string, unknown>), path: CANONICAL_AVATAR_PREFIX + path.slice(V0_AVATAR_PREFIX.length) };
}

async function processMember(m: V0Member, drifts: Drift[]): Promise<RowOutcome> {
  if (m.id === "woon") {
    m.name = "Noop analyst";
  }

  const existing = (
    await sql`
      SELECT status, name, tagline, lens, mandate, biases, voice_md, mode, submit, operator, avatar
      FROM swarm_members WHERE id = ${m.id}
    `
  )[0] as Record<string, unknown> | undefined;

  const avatar = canonicalizeAvatar(m.avatar);
  const fields: FieldSpec[] = [
    { column: "status", kind: "text", expected: m.status ?? "inactive" },
    { column: "name", kind: "text", expected: m.name },
    { column: "tagline", kind: "text", expected: m.tagline },
    { column: "lens", kind: "text", expected: m.lens },
    { column: "mandate", kind: "text", expected: m.mandate },
    { column: "biases", kind: "json", expected: m.biases },
    { column: "voice_md", kind: "text", expected: m.voice_md },
    { column: "mode", kind: "text", expected: m.mode },
    { column: "submit", kind: "json", expected: m.submit },
    { column: "operator", kind: "text", expected: m.operator },
    { column: "avatar", kind: "json", expected: avatar },
  ];

  if (!existing) {
    await sql`
      INSERT INTO swarm_members (id, status, name, tagline, lens, mandate, biases, voice_md, mode, submit, operator, avatar)
      VALUES (
        ${m.id}, ${m.status ?? "inactive"}, ${m.name}, ${m.tagline ?? null}, ${m.lens ?? null}, ${m.mandate ?? null},
        ${sql.json(jsonValue(m.biases ?? null))}, ${m.voice_md ?? ""}, ${m.mode ?? null},
        ${sql.json(jsonValue(m.submit ?? null))}, ${m.operator ?? null}, ${sql.json(jsonValue(avatar))}
      )
    `;
    return "inserted";
  }

  // A column that is NULL on the existing row is FILLED from the archive, not
  // reported as drift — column-level "append-only: fills in what's missing",
  // the same principle the header states for whole rows. Nothing non-NULL is
  // ever touched, so the never-overwrite contract is unchanged.
  //
  // This is what makes the row order-independent. src/swarm/roster-seed.ts's
  // seedLiveRoster() writes only the profile columns the committed manifests
  // own; it deliberately leaves voice_md null (the manifests keep the voice
  // document beside them) and never writes `submit`. On a deployment that
  // seats the live roster before this backfill runs — the order `bun run
  // prod-bootstrap` itself produces, since step 1's migrate() calls seed() —
  // athena and robotmoney already exist with those two columns empty, and
  // without this the archive's own values are reported as drift on rows
  // nobody edited (issue #540).
  const fillable = fields.filter((f) => existing[f.column] === null && (f.expected ?? null) !== null);
  for (const f of fillable) {
    const value = (f.kind === "json" ? sql.json(jsonValue(f.expected as never)) : f.expected) as never;
    await sql`UPDATE swarm_members SET ${sql(f.column)} = ${value} WHERE id = ${m.id}`;
    existing[f.column] = f.expected;
  }
  if (fillable.length > 0) {
    console.log(
      `[v0-seed-bootstrap] swarm_members id=${m.id}: filled ${fillable.length} empty column(s) from the archive — ` +
        fillable.map((f) => f.column).join(", "),
    );
  }

  const rowDrifts = diffRow("swarm_members", `id=${m.id}`, fields, existing);
  if (rowDrifts.length === 0) return "unchanged";
  drifts.push(...rowDrifts);
  return "drift";
}

async function processSubject(s: V0Subject, drifts: Drift[]): Promise<RowOutcome> {
  if (s.id === "woon") {
    s.name = "Woon Treasury Allocation";
  } else if (s.id === "robotmoney-treasury") {
    s.name = "RM Protocol Treasury";
  }

  const existing = (
    await sql`
      SELECT status, name, operator, homepage, x_handle, thesis_blurb, wallets, nft_contracts, source,
             recommendation_type, linked_member_id, structural_notes, last_reviewed
      FROM swarm_subjects WHERE id = ${s.id}
    `
  )[0] as Record<string, unknown> | undefined;

  const fields: FieldSpec[] = [
    { column: "status", kind: "text", expected: s.status ?? "active" },
    { column: "name", kind: "text", expected: s.name },
    { column: "operator", kind: "text", expected: s.operator },
    { column: "homepage", kind: "text", expected: s.homepage },
    { column: "x_handle", kind: "text", expected: s.x_handle },
    { column: "thesis_blurb", kind: "text", expected: s.thesis_blurb },
    { column: "wallets", kind: "json", expected: s.wallets },
    { column: "nft_contracts", kind: "json", expected: s.nft_contracts },
    { column: "source", kind: "json", expected: s.source },
    { column: "recommendation_type", kind: "text", expected: s.recommendation_type },
    { column: "linked_member_id", kind: "text", expected: s.linked_member_id },
    { column: "structural_notes", kind: "json", expected: s.structural_notes },
    { column: "last_reviewed", kind: "date", expected: s.last_reviewed },
  ];

  if (!existing) {
    await sql`
      INSERT INTO swarm_subjects (
        id, status, name, operator, homepage, x_handle, thesis_blurb,
        wallets, nft_contracts, source, recommendation_type, linked_member_id, structural_notes, last_reviewed
      )
      VALUES (
        ${s.id}, ${s.status ?? "active"}, ${s.name}, ${s.operator ?? null}, ${s.homepage ?? null}, ${s.x_handle ?? null}, ${s.thesis_blurb ?? null},
        ${sql.json(jsonValue(s.wallets ?? null))}, ${sql.json(jsonValue(s.nft_contracts ?? null))},
        ${sql.json(jsonValue(s.source ?? null))}, ${s.recommendation_type ?? null}, ${s.linked_member_id ?? null},
        ${sql.json(jsonValue(s.structural_notes ?? null))}, ${s.last_reviewed ?? null}
      )
    `;
    return "inserted";
  }

  const rowDrifts = diffRow("swarm_subjects", `id=${s.id}`, fields, existing);
  if (rowDrifts.length === 0) return "unchanged";
  drifts.push(...rowDrifts);
  return "drift";
}

// The v0 `date` field (e.g. "2026-06-23") interpreted as UTC midnight — the
// same conversion migration 0022_committee_session_convened_at.sql used to
// backfill convened_at from the old `date` column (`date::timestamptz`,
// which for a bare date is UTC midnight), so this is the idiomatic
// date->convened_at conversion in this codebase.
function convenedAtFromDate(date: string): string {
  return `${date}T00:00:00Z`;
}

async function processSession(sess: V0Session, drifts: Drift[]): Promise<RowOutcome> {
  const convenedAt = convenedAtFromDate(sess.date);
  const publishedAt = sess.generated_at;

  if (sess.subject_id === "woon") {
    sess.subject_name = "Woon Treasury Allocation";
  } else if (sess.subject_id === "robotmoney-treasury") {
    sess.subject_name = "RM Protocol Treasury";
  }

  if (sess.takes) {
    for (const take of sess.takes) {
      if (take.member_id === "woon") take.member_name = "Noop analyst";
    }
  }

  const existing = (
    await sql`
      SELECT subject_name, regime_summary, subject_snapshot_total_value_usd, synthesis, swarm_recommendation,
             social_draft_id, generated_at, state, published_at
      FROM swarm_sessions
      WHERE subject_id = ${sess.subject_id} AND convened_at = ${convenedAt}
    `
  )[0] as Record<string, unknown> | undefined;

  const fields: FieldSpec[] = [
    { column: "subject_name", kind: "text", expected: sess.subject_name },
    { column: "regime_summary", kind: "json", expected: sess.regime_summary },
    { column: "subject_snapshot_total_value_usd", kind: "numeric", expected: sess.subject_snapshot_total_value_usd },
    { column: "synthesis", kind: "text", expected: sess.synthesis },
    { column: "swarm_recommendation", kind: "json", expected: sess.committee_recommendation },
    { column: "social_draft_id", kind: "text", expected: sess.social_draft_id },
    { column: "generated_at", kind: "timestamp", expected: sess.generated_at },
    { column: "state", kind: "text", expected: "published" },
    { column: "published_at", kind: "timestamp", expected: publishedAt },
  ];

  const naturalKey = `subject_id=${sess.subject_id}, convened_at=${convenedAt}`;

  if (!existing) {
    await sql`
      INSERT INTO swarm_sessions (
        subject_id, convened_at, subject_name, regime_summary, subject_snapshot_total_value_usd,
        synthesis, swarm_recommendation, social_draft_id, generated_at, state, published_at
      )
      VALUES (
        ${sess.subject_id}, ${convenedAt}, ${sess.subject_name ?? null}, ${sql.json(jsonValue(sess.regime_summary ?? null))},
        ${sess.subject_snapshot_total_value_usd ?? null}, ${sess.synthesis ?? null},
        ${sql.json(jsonValue(sess.committee_recommendation ?? null))}, ${sess.social_draft_id ?? null}, ${sess.generated_at ?? null},
        'published', ${publishedAt ?? null}
      )
    `;
    return "inserted";
  }

  const rowDrifts = diffRow("swarm_sessions", naturalKey, fields, existing);
  if (rowDrifts.length === 0) return "unchanged";
  drifts.push(...rowDrifts);
  return "drift";
}

// ── Legacy takes → swarm_recommendations ────────────────────────────────────
//
// v0's takes are unsigned narrative prose. swarm_recommendations is the only
// take store v1 has (committee_takes was dropped in 0006 as a prototype
// remnant) and it requires nonce/payload/signature NOT NULL. Three ways to
// resolve that, and only one is honest:
//
//   * add a legacy_takes column — rejected. It bends v1's data model around
//     v0's shape, and forks every read path into "signed" and "legacy"
//     forever.
//   * write a placeholder signature ('legacy', '', a hash) — rejected. It
//     satisfies NOT NULL by lying: the column means "the member signed this".
//   * SIGN THEM, HERE, AT IMPORT — what this does. A real Ed25519 signature
//     over the real canonical payload, made with an archival key that is
//     deliberately NOT registered in swarm_member_keys.
//
// That last point is what makes it truthful, and it needs no schema change and
// no read-path change: toVerifiedTake() (projections.ts:152) ignores the stored
// `verified` column and re-verifies at READ time against the member's currently
// registered active key. Our archival key is not that key, so every one of
// these rows reports verified:false on its own, forever, without anything
// downstream having to know v0 existed.
//
// verified:false is NOT, however, the same statement as "this member's
// signature failed to check out", and the read surfaces used to render it as
// exactly that. The nonce prefix below is what lets them tell the difference
// (projections.ts's `archival` flag) — these takes were published before member
// key registration existed, so there is no member signature to have failed.
//
// Ed25519 is deterministic (RFC 8032): the same key over the same payload
// always yields the same signature, so re-running the bootstrap is a clean
// no-op rather than churning the signature column.
const V0_IMPORT_NONCE_PREFIX = V0_ARCHIVE_NONCE_PREFIX;

// The archival key is PUBLISHED (v0-archive.ts), not generated per run and not
// required from the environment. The earlier design demanded an operator key
// and, when the demo could not supply one, minted a throwaway per boot and
// discarded it — so the same 216 rows were signed by a different key in every
// deployment, by a key nobody held, and an import interrupted under one key and
// resumed under another was undetectable. A published key makes the signature
// reproducible everywhere, which is what lets it be drift-checked below.
async function loadArchivalSigningKey(): Promise<CryptoKey> {
  const b64 = process.env.V0_ARCHIVE_SIGNING_KEY || V0_ARCHIVE_SIGNING_KEY_PKCS8_B64;
  return crypto.subtle.importKey("pkcs8", Buffer.from(b64, "base64"), "Ed25519", false, ["sign"]);
}

// The canonical submission bytes for a v0 take. Deliberately the SAME shape a
// live member signs (contract/src/signing.js canonicalizeSubmission), so these
// rows are structurally indistinguishable from any other recommendation —
// which is the whole point of importing them here rather than somewhere else.
function canonicalSubmissionFor(sess: V0Session, take: V0Take): Record<string, unknown> {
  return {
    memberId: take.member_id,
    date: sess.date,
    subjectId: sess.subject_id,
    nonce: `${V0_IMPORT_NONCE_PREFIX}-${sess.date}-${sess.subject_id}`,
    stance: take.stance,
    confidence: take.confidence,
    body: take.body ?? "",
    memoUrl: "",
  };
}

async function processTake(
  sess: V0Session,
  take: V0Take,
  sessionId: string,
  key: CryptoKey,
  drifts: Drift[],
): Promise<RowOutcome> {
  const submission = canonicalSubmissionFor(sess, take);
  const nonce = submission.nonce as string;

  // WHEN v0 FILED THIS TAKE. `received_at` is NOT NULL DEFAULT now()
  // (0004_committee.sql:41), so omitting it does not leave the column empty —
  // it stamps every archive row with the bootstrap run's wall clock and calls
  // that the filing time. swarm_recommendations is the append-only canonical
  // take store and /swarm/takes/<id> renders this as "Filed <date> <HH:MM>
  // UTC", so that is a falsified public receipt, written somewhere the fix is
  // a DELETE rather than a rerun. The true value was in the artifact the whole
  // time: all 216 takes carry a distinct `generated_at`.
  //
  // No fallback past the session's own generated_at: a take with neither
  // timestamp hits the NOT NULL and fails the import loudly, which is the
  // correct outcome. Silently substituting the run clock is the bug.
  const receivedAt = take.generated_at ?? sess.generated_at ?? null;

  // Ed25519 is deterministic, so this is the same 64 bytes on every run for
  // the same content and key — which is what makes `signature` safe to
  // drift-check rather than merely assert non-null. Computed before the
  // lookup so both branches share it.
  const signature = await signMessage(canonicalizeSubmission(submission as never), key);

  const existing = (
    await sql`
      SELECT stance, confidence, body, nonce, payload, signature, received_at
      FROM swarm_recommendations WHERE session_id = ${sessionId} AND member_id = ${take.member_id}
    `
  )[0] as Record<string, unknown> | undefined;

  const fields: FieldSpec[] = [
    { column: "stance", kind: "text", expected: take.stance },
    { column: "confidence", kind: "numeric", expected: take.confidence },
    { column: "body", kind: "text", expected: take.body },
    { column: "nonce", kind: "text", expected: nonce },
    { column: "payload", kind: "json", expected: submission },
    // Without this, a row imported under a DIFFERENT archival key reads as
    // "unchanged" forever — an interrupted-and-resumed import signed by two
    // keys was invisible.
    { column: "signature", kind: "text", expected: signature },
    { column: "received_at", kind: "timestamp", expected: receivedAt },
  ];
  const naturalKey = `session=${sess.subject_id}/${sess.date}, member_id=${take.member_id}`;

  if (!existing) {
    await sql`
      INSERT INTO swarm_recommendations
        (session_id, member_id, subject_id, date, nonce, stance, confidence, body, payload, signature, verified, received_at)
      VALUES (
        ${sessionId}, ${take.member_id}, ${sess.subject_id}, ${sess.date}, ${nonce},
        ${take.stance ?? null}, ${take.confidence ?? null}, ${take.body ?? null},
        ${sql.json(jsonValue(submission))}, ${signature}, false, ${receivedAt}
      )
    `;
    return "inserted";
  }

  const rowDrifts = diffRow("swarm_recommendations", naturalKey, fields, existing);
  if (rowDrifts.length === 0) return "unchanged";
  drifts.push(...rowDrifts);
  return "drift";
}

// ── Subject snapshots ───────────────────────────────────────────────────────
// v0 wrote `fetched_at` and `source_type` alongside these; v1 has no column
// for either, so they are dropped HERE rather than in the artifact — the
// artifact keeps saying what v0 said, and the schema stays clean.
async function processSnapshot(snap: V0Snapshot, drifts: Drift[]): Promise<RowOutcome> {
  const existing = (
    await sql`
      SELECT total_value_usd, positions, wallets, notable
      FROM swarm_subject_snapshots WHERE subject_id = ${snap.subject_id} AND date = ${snap.date}
    `
  )[0] as Record<string, unknown> | undefined;

  const fields: FieldSpec[] = [
    { column: "total_value_usd", kind: "numeric", expected: snap.total_value_usd },
    { column: "positions", kind: "json", expected: snap.positions },
    { column: "wallets", kind: "json", expected: snap.wallets },
    { column: "notable", kind: "json", expected: snap.notable },
  ];
  const naturalKey = `subject_id=${snap.subject_id}, date=${snap.date}`;

  if (!existing) {
    await sql`
      INSERT INTO swarm_subject_snapshots (subject_id, date, total_value_usd, positions, wallets, notable)
      VALUES (
        ${snap.subject_id}, ${snap.date}, ${snap.total_value_usd ?? null},
        ${sql.json(jsonValue(snap.positions ?? null))}, ${sql.json(jsonValue(snap.wallets ?? null))},
        ${sql.json(jsonValue(snap.notable ?? null))}
      )
    `;
    return "inserted";
  }

  const rowDrifts = diffRow("swarm_subject_snapshots", naturalKey, fields, existing);
  if (rowDrifts.length === 0) return "unchanged";
  drifts.push(...rowDrifts);
  return "drift";
}

// ── Briefs ──────────────────────────────────────────────────────────────────
async function processBrief(brief: V0Brief, drifts: Drift[]): Promise<RowOutcome> {
  const existing = (
    await sql`SELECT body FROM swarm_briefs WHERE date = ${brief.date} AND subject_id = ${brief.subject_id}`
  )[0] as Record<string, unknown> | undefined;

  const fields: FieldSpec[] = [{ column: "body", kind: "json", expected: brief.body }];
  const naturalKey = `date=${brief.date}, subject_id=${brief.subject_id}`;

  if (!existing) {
    await sql`
      INSERT INTO swarm_briefs (date, subject_id, body)
      VALUES (${brief.date}, ${brief.subject_id}, ${sql.json(jsonValue(brief.body ?? null))})
    `;
    return "inserted";
  }

  const rowDrifts = diffRow("swarm_briefs", naturalKey, fields, existing);
  if (rowDrifts.length === 0) return "unchanged";
  drifts.push(...rowDrifts);
  return "drift";
}

// The core, testable bootstrap: loads the archive, applies it to the
// database, and returns a structured result — no process.exitCode side
// effect, so a caller (test or CLI) decides what to do with the outcome.
export async function runV0SeedBootstrap(): Promise<V0BootstrapResult> {
  const { payload, manifest } = await loadV0Archive();
  console.log(
    `[v0-seed-bootstrap] loaded archive: sourceRepo=${manifest.sourceRepo} sourceCommit=${manifest.sourceCommit} ` +
      `extractedAt=${manifest.extractedAt} members=${manifest.counts.members} subjects=${manifest.counts.subjects} sessions=${manifest.counts.sessions}`,
  );

  const drifts: Drift[] = [];

  // ── 1. Members ────────────────────────────────────────────────────────
  let membersInserted = 0;
  let membersUnchanged = 0;
  let membersDrifted = 0;
  for (const m of payload.members) {
    const outcome = await processMember(m, drifts);
    if (outcome === "inserted") membersInserted++;
    else if (outcome === "unchanged") membersUnchanged++;
    else membersDrifted++;
  }
  console.log(
    `[v0-seed-bootstrap] members: inserted=${membersInserted} unchanged=${membersUnchanged} drifted=${membersDrifted} (of ${payload.members.length})`,
  );

  // ── 2. Subjects (depend on nothing new here; FK from sessions below) ───
  let subjectsInserted = 0;
  let subjectsUnchanged = 0;
  let subjectsDrifted = 0;
  for (const s of payload.subjects) {
    const outcome = await processSubject(s, drifts);
    if (outcome === "inserted") subjectsInserted++;
    else if (outcome === "unchanged") subjectsUnchanged++;
    else subjectsDrifted++;
  }
  console.log(
    `[v0-seed-bootstrap] subjects: inserted=${subjectsInserted} unchanged=${subjectsUnchanged} drifted=${subjectsDrifted} (of ${payload.subjects.length})`,
  );

  // Current live roster (post member-processing above) — used to validate
  // every legacy_takes[].member_id below without crashing on a dangling
  // reference (warn only).
  const knownMemberIds = new Set((await sql<{ id: string }[]>`SELECT id FROM swarm_members`).map((r) => r.id));

  // ── 3. Sessions + their takes (FK to subjects and members) ───────────────
  // Takes are processed inline per session, immediately after the session row
  // exists, so a take can never reference a session id that was not just
  // resolved. The archival signing key is loaded ONCE, before the loop, so a
  // missing V0_ARCHIVE_SIGNING_KEY fails before any row is written rather than
  // part-way through the import.
  const signingKey = await loadArchivalSigningKey();
  const sessions = tally();
  const takes = tally();
  for (const sess of payload.sessions) {
    const outcome = await processSession(sess, drifts);
    sessions.record(outcome);

    const sessionId = (
      await sql<{ id: string }[]>`
        SELECT id FROM swarm_sessions
        WHERE subject_id = ${sess.subject_id} AND convened_at = ${convenedAtFromDate(sess.date)}
      `
    )[0]?.id;
    if (!sessionId) {
      console.warn(
        `[v0-seed-bootstrap] WARNING: session ${sess.subject_id}/${sess.date} has no row after processing — skipping its ${sess.takes?.length ?? 0} take(s)`,
      );
      continue;
    }

    for (const take of sess.takes ?? []) {
      // A dangling member reference is warned about, never fatal — but it also
      // cannot be inserted, since swarm_recommendations.member_id is a FK.
      if (!take.member_id || !knownMemberIds.has(take.member_id)) {
        console.warn(
          `[v0-seed-bootstrap] WARNING: session ${sess.subject_id}/${sess.date} take references unknown member_id=${JSON.stringify(take.member_id)} (not in swarm_members) — skipped`,
        );
        continue;
      }
      takes.record(await processTake(sess, take, sessionId, signingKey, drifts));
    }
  }
  console.log(
    `[v0-seed-bootstrap] sessions: inserted=${sessions.inserted} unchanged=${sessions.unchanged} drifted=${sessions.drifted} (of ${payload.sessions.length})`,
  );
  console.log(
    `[v0-seed-bootstrap] takes: inserted=${takes.inserted} unchanged=${takes.unchanged} drifted=${takes.drifted} (of ${takes.total}) ` +
      `— signed with the archival key, verified=false (not a member key)`,
  );

  // ── 4. Subject snapshots (FK to subjects) ────────────────────────────────
  const snapshots = tally();
  for (const snap of payload.snapshots) snapshots.record(await processSnapshot(snap, drifts));
  console.log(
    `[v0-seed-bootstrap] snapshots: inserted=${snapshots.inserted} unchanged=${snapshots.unchanged} drifted=${snapshots.drifted} (of ${payload.snapshots.length})`,
  );

  // ── 5. Briefs (FK to subjects) ───────────────────────────────────────────
  const briefs = tally();
  for (const b of payload.briefs) briefs.record(await processBrief(b, drifts));
  console.log(
    `[v0-seed-bootstrap] briefs: inserted=${briefs.inserted} unchanged=${briefs.unchanged} drifted=${briefs.drifted} (of ${payload.briefs.length})`,
  );

  // ── Summary — attempted every entity above BEFORE deciding the outcome,
  // so a drift earlier in the run never suppresses inserts that come after it.
  if (drifts.length > 0) {
    console.error(
      `[v0-seed-bootstrap] ${drifts.length} inconsistenc${drifts.length === 1 ? "y" : "ies"} detected — existing row(s) differ ` +
        `from the archive and were NOT overwritten:`,
    );
    for (const d of drifts) {
      console.error(
        `  - ${d.entity} (${d.naturalKey}) field "${d.field}": existing=${JSON.stringify(d.oldValue)} incoming=${JSON.stringify(d.newValue)}`,
      );
    }
  } else {
    console.log("[v0-seed-bootstrap] no inconsistencies detected — bootstrap complete.");
  }

  const strip = (c: ReturnType<typeof tally>): EntityCounts => ({
    inserted: c.inserted,
    unchanged: c.unchanged,
    drifted: c.drifted,
    total: c.total,
  });

  return {
    members: { inserted: membersInserted, unchanged: membersUnchanged, drifted: membersDrifted, total: payload.members.length },
    subjects: { inserted: subjectsInserted, unchanged: subjectsUnchanged, drifted: subjectsDrifted, total: payload.subjects.length },
    sessions: strip(sessions),
    takes: strip(takes),
    snapshots: strip(snapshots),
    briefs: strip(briefs),
    drifts,
  };
}

// Thin CLI entrypoint: run the core bootstrap and translate its result into
// the process exit code (never the other way around) — kept separate from
// runV0SeedBootstrap() so tests can assert on the structured result directly
// without mutating global process state.
export async function main(): Promise<void> {
  const result = await runV0SeedBootstrap();
  if (result.drifts.length > 0) process.exitCode = 1;
}

// Run directly: `bun run scripts/v0-seed-bootstrap.ts`
if (import.meta.url === `file://${process.argv[1]}`) {
  main()
    .then(closeDb)
    .catch((err) => {
      console.error(err);
      process.exitCode = 1;
      return closeDb();
    });
}
