// `bun run golden:regenerate` rebuilds the SDK test fixtures and the golden report
// from the backend's vendored raw floor, deterministically. Dev-only script: it
// reads and writes local files and lives outside src/, so the SDK stays pure.
//
// Rule (documented in tests/fixtures/PROVENANCE.md, which this script writes):
//   1. Take every row of backend/tests/fixtures/regime/raw-indicator-history.csv.gz.
//   2. Add the extras from regime-extras.json.gz, mapped spx -> SPX, eth -> ETH,
//      tbill3m -> TBILL3M.
//   3. Keep rows dated on or after CUT_DATE (2022-01-01).
//   4. Sort by date, then indicator name, bytewise. Add source = "fixture".
//   5. Write the CSV (trailing newline) and the JSON (compact, no trailing newline).
//   6. Regenerate tests/golden/regime-report.json from runRegime over that CSV.
// `--check` recomputes everything in memory and exits 1 if any file would change.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";
import { parseRawHistory, toHistory } from "../src/input/load.ts";
import { buildReport, runRegime } from "../src/run.ts";

const CUT_DATE = "2022-01-01";
const HERE = dirname(fileURLToPath(import.meta.url));
const SDK = join(HERE, "..");
const BACKEND_FIX = join(SDK, "..", "..", "backend", "tests", "fixtures", "regime");
const OUT = {
  csv: join(SDK, "tests/fixtures/raw-indicator-history.csv"),
  json: join(SDK, "tests/fixtures/raw-indicator-history.json"),
  prov: join(SDK, "tests/fixtures/PROVENANCE.md"),
  golden: join(SDK, "tests/golden/regime-report.json"),
};
const EXTRAS: Array<[key: "spx" | "eth" | "tbill3m", id: string]> = [
  ["spx", "SPX"],
  ["eth", "ETH"],
  ["tbill3m", "TBILL3M"],
];

const sha = (b: Buffer | string) => createHash("sha256").update(b).digest("hex");
const cmp = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

const rawGz = readFileSync(join(BACKEND_FIX, "raw-indicator-history.csv.gz"));
const extrasGz = readFileSync(join(BACKEND_FIX, "regime-extras.json.gz"));
const floorLines = gunzipSync(rawGz).toString("utf8").split("\n").slice(1).filter(Boolean);
const extras = JSON.parse(gunzipSync(extrasGz).toString("utf8")) as Record<string, Array<{ date: string; value: number }>>;

type Row = { date: string; indicator: string; value: string };
const rows: Row[] = [];
for (const line of floorLines) {
  const [date, indicator, value] = line.split(",");
  rows.push({ date, indicator, value });
}
for (const [key, id] of EXTRAS) for (const r of extras[key]) rows.push({ date: r.date, indicator: id, value: String(r.value) });
const kept = rows.filter((r) => r.date >= CUT_DATE);
kept.sort((a, b) => cmp(a.date, b.date) || cmp(a.indicator, b.indicator));
const dup = kept.findIndex((r, i) => i > 0 && r.date === kept[i - 1].date && r.indicator === kept[i - 1].indicator);
if (dup >= 0) throw new Error(`duplicate (date, indicator) at ${kept[dup].date} ${kept[dup].indicator}`);

const csv = "date,indicator,value,source\n" + kept.map((r) => `${r.date},${r.indicator},${r.value},fixture`).join("\n") + "\n";
const json = JSON.stringify(kept.map((r) => ({ date: r.date, indicator: r.indicator, value: Number(r.value), source: "fixture" })));

const report = buildReport(runRegime(toHistory(parseRawHistory(csv))));
const golden = JSON.stringify(report, null, 2) + "\n";

const perId: Record<string, number> = {};
for (const r of kept) perId[r.indicator] = (perId[r.indicator] ?? 0) + 1;
const ids = Object.keys(perId).sort(cmp);
const lastDate = kept[kept.length - 1].date;

const prov = `# Fixture provenance

Generated by \`bun run golden:regenerate\` (packages/analyst-sdk/scripts/golden-regenerate.ts). Do not edit by hand.

## Source

- \`backend/tests/fixtures/regime/raw-indicator-history.csv.gz\`, sha256 \`${sha(rawGz)}\`, ${floorLines.length} rows.
- \`backend/tests/fixtures/regime/regime-extras.json.gz\`, sha256 \`${sha(extrasGz)}\`, rows: ${EXTRAS.map(([k, id]) => `${k} -> ${id} ${extras[k].length}`).join(", ")}.

## Rule

1. Take every row of the raw floor and add the extras, mapped spx to SPX, eth to ETH and tbill3m to TBILL3M.
2. Keep rows dated on or after the cut date ${CUT_DATE}.
3. Sort by date, then by indicator name (bytewise). Set \`source\` to \`fixture\` on every row.
4. CSV: header \`date,indicator,value,source\`, trailing newline. JSON: compact array of the same rows, no trailing newline. Values are copied as the source text (extras use the JS number string).
5. The golden \`tests/golden/regime-report.json\` is the default \`buildReport(runRegime(...))\` output over the CSV. It is cross-checked against the original JS reference by \`backend/tests/analyst-sdk-golden-reference.test.ts\`.

The rule reproduces the fixture committed before this script existed exactly, as a row set and in byte layout.

## Output

- Cut date: ${CUT_DATE}. Last date: ${lastDate}. Indicators: ${ids.length}.
- Rows: ${kept.length}.
- \`raw-indicator-history.csv\` sha256 \`${sha(csv)}\`.
- \`raw-indicator-history.json\` sha256 \`${sha(json)}\`.
- \`../golden/regime-report.json\` sha256 \`${sha(golden)}\`.

| indicator | rows |
| --- | ---: |
${ids.map((i) => `| ${i} | ${perId[i]} |`).join("\n")}

## Regenerate

\`\`\`
cd packages/analyst-sdk
bun run golden:regenerate          # rewrite fixtures, this file and the golden
bun run golden:regenerate --check  # exit 1 if any of them would change
\`\`\`
`;

const outputs: Array<[string, string]> = [[OUT.csv, csv], [OUT.json, json], [OUT.prov, prov], [OUT.golden, golden]];
if (process.argv.includes("--check")) {
  const stale = outputs.filter(([p, t]) => !existsSync(p) || readFileSync(p, "utf8") !== t).map(([p]) => p);
  if (stale.length) {
    console.error(`golden:regenerate --check: stale\n${stale.join("\n")}`);
    process.exit(1);
  }
  console.log("golden:regenerate --check: up to date");
} else {
  for (const [p, t] of outputs) writeFileSync(p, t);
  console.log(`wrote ${outputs.length} files, ${kept.length} rows, last date ${lastDate}`);
}
