// Predictive-power correlations — ported VERBATIM from agentjuno/robotmoney
// scripts/regime/update.js (computeCorrelations ~L531-605 + spearman/ranks/pearson/
// toDateMap/lookupPrice/addDaysIso). Pure and deterministic: same inputs → same
// output. Byte-fidelity to the original JS is proven in
// backend/tests/backtest-correlations-fidelity.test.ts against a vendored reference
// generated by the original JS over the same raw fixture.
//
// For each index (composite + each panel index) we compute the rank correlation
// (Spearman ρ) between the index level on day t and:
//   forward:    the asset log-return over the next {30,90,180} calendar days
//               (the PREDICTIVE measure).
//   concurrent: today's asset log-price level (an alignment sanity check).
// `spearman` returns NaN for <10 pairs; rho is nulled via nullIfNaN.
import type { RegimeComputeResult } from "./compute.ts";
import type { Point } from "../types.ts";
import { PANELS } from "./indicators.ts";

export const CORR_HORIZONS_DAYS = [30, 90, 180] as const;
export const CORR_ASSETS = ["spx", "eth"] as const;

export interface CorrelationCell {
  rho: number | null;
  n: number;
}
export interface CorrelationsPayload {
  // forward[indexName][`${asset}_${h}d`] and concurrent[indexName][asset]
  forward: Record<string, Record<string, CorrelationCell>>;
  concurrent: Record<string, Record<string, CorrelationCell>>;
}

// The extras the correlations need: daily SPX (^GSPC) and ETH (ETH-USD) price
// levels as {date,value}[]. NOT registry indicators (the raw floor stores derived
// ratios, not price levels) — sourced via AnalyticsDataSource.fetchBacktestExtras.
export interface CorrelationExtras {
  spx: Point[];
  eth: Point[];
}

const nullIfNaN = (v: number): number | null => (Number.isFinite(v) ? v : null);

export function computeCorrelations(
  dateAxis: string[],
  result: RegimeComputeResult,
  extras: CorrelationExtras,
): CorrelationsPayload {
  const indices: Record<string, number[]> = { composite: result.composite };
  for (const p of result.panels || PANELS) indices[p] = result.panelIndices[p];
  const priceMaps: Record<string, Map<string, number>> = {
    spx: toDateMap(extras.spx),
    eth: toDateMap(extras.eth),
  };
  const out: CorrelationsPayload = { forward: {}, concurrent: {} };
  for (const [idxName, series] of Object.entries(indices)) {
    out.forward[idxName] = {};
    out.concurrent[idxName] = {};
    for (const asset of CORR_ASSETS) {
      // Forward-return correlations.
      for (const h of CORR_HORIZONS_DAYS) {
        const pairs: [number, number][] = [];
        for (let i = 0; i < dateAxis.length; i++) {
          const x = series[i];
          if (!Number.isFinite(x)) continue;
          const d = dateAxis[i];
          const p0 = lookupPrice(priceMaps[asset], d, -1);
          const p1 = lookupPrice(priceMaps[asset], addDaysIso(d, h), +1);
          if (p0 == null || p1 == null || p0 <= 0 || p1 <= 0) continue;
          pairs.push([x, Math.log(p1 / p0)]);
        }
        out.forward[idxName][`${asset}_${h}d`] = {
          rho: nullIfNaN(spearman(pairs)),
          n: pairs.length,
        };
      }
      // Concurrent (today's index vs today's log-price).
      const cPairs: [number, number][] = [];
      for (let i = 0; i < dateAxis.length; i++) {
        const x = series[i];
        if (!Number.isFinite(x)) continue;
        const p = lookupPrice(priceMaps[asset], dateAxis[i], -1);
        if (p == null || p <= 0) continue;
        cPairs.push([x, Math.log(p)]);
      }
      out.concurrent[idxName][asset] = {
        rho: nullIfNaN(spearman(cPairs)),
        n: cPairs.length,
      };
    }
  }
  return out;
}

export function toDateMap(series: Point[] | undefined): Map<string, number> {
  const m = new Map<string, number>();
  if (Array.isArray(series)) for (const p of series) m.set(p.date, p.value);
  return m;
}

export function lookupPrice(
  map: Map<string, number>,
  iso: string,
  dir: number,
  maxStep = 7,
): number | null {
  let d = iso;
  for (let i = 0; i <= maxStep; i++) {
    const v = map.get(d);
    if (v !== undefined && Number.isFinite(v)) return v;
    d = addDaysIso(d, dir);
  }
  return null;
}

export function addDaysIso(iso: string, n: number): string {
  const d = new Date(iso + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
}

export function spearman(pairs: [number, number][]): number {
  if (pairs.length < 10) return NaN;
  const rx = ranks(pairs.map((p) => p[0]));
  const ry = ranks(pairs.map((p) => p[1]));
  return pearson(rx, ry);
}

// Average-rank of ties (fractional midrank), 1-based — matches the original.
export function ranks(arr: number[]): number[] {
  const idx = arr.map((v, i) => [v, i] as [number, number]).sort((a, b) => a[0] - b[0]);
  const out = new Array<number>(arr.length);
  let i = 0;
  while (i < idx.length) {
    let j = i;
    while (j + 1 < idx.length && idx[j + 1][0] === idx[i][0]) j++;
    const avg = (i + j) / 2 + 1;
    for (let k = i; k <= j; k++) out[idx[k][1]] = avg;
    i = j + 1;
  }
  return out;
}

export function pearson(a: number[], b: number[]): number {
  const n = a.length;
  if (n < 2) return NaN;
  let sa = 0;
  let sb = 0;
  for (let i = 0; i < n; i++) {
    sa += a[i];
    sb += b[i];
  }
  const ma = sa / n;
  const mb = sb / n;
  let num = 0;
  let da2 = 0;
  let db2 = 0;
  for (let i = 0; i < n; i++) {
    const da = a[i] - ma;
    const db = b[i] - mb;
    num += da * db;
    da2 += da * da;
    db2 += db * db;
  }
  const denom = Math.sqrt(da2 * db2);
  return denom > 0 ? num / denom : NaN;
}
