export function path(template: string, params?: Record<string, string | number>): string;

export const ROUTES: {
  health: string;
  comments: { list: string; create: string };
  dashboards: {
    regimeSnapshots: string;
    researchSignal: string;
    vaultEconomics: string;
    walletBalances: string;
    buybacks: string;
    tokenMetrics: string;
    walletSleeves: string;
    allocation: string;
    entities: string;
    overview: string;
    list2: string;
    leaderboard: string;
    submissions: string;
    activity: string;
    agents: string;
    agentDetail: string;
    coins: string;
    vaults: string;
    wallets: string;
    coinDetail: string;
    vaultDetail: string;
    walletDetail: string;
  };
  projects: {
    list: string;
    detail: string;
    adminUpdate: string;
  };
  swarm: {
    members: string;
    waitlist: string;
    member: string;
    memberTakes: string;
    memberProfile: string;
    subject: string;
    subjectSnapshots: string;
    sessions: string;
    session: string;
    sessionById: string;
    take: string;
    takePermalink: string;
    openSession: string;
    brief: string;
    signingPayload: string;
    memos: string;
    memo: string;
    verifyToken: string;
    apply: string;
    applyStatus: string;
    applicationStatus: string;
    claimChallenge: string;
    claimToken: string;
    register: string;
    regime: string;
    submit: string;
    admin: {
      action: string;
      activate: string;
      /** `reset` removed — it wiped published session history (see routes.js). */
      regime: string;
      subject: string;
      subjectFixtures: string;
      open: string;
      brief: string;
      close: string;
      aggregate: string;
      publish: string;
      enqueueJob: string;
      subjects: string;
      subjectUpdate: string;
      subjectDeactivate: string;
      members: string;
      applications: string;
      memberReview: string;
      memberDeactivate: string;
      memberReactivate: string;
      memberRotateKey: string;
      sessionCreate: string;
      sessionRoster: string;
      rosterAdd: string;
      rosterExcuse: string;
      rosterRestore: string;
      sessionCancel: string;
      sessionClose: string;
      sessionReopen: string;
      sessionAggregate: string;
      sessionPublish: string;
      audit: string;
    };
  };
  analytics: {
    readiness: string;
    rawHistory: string;
    rawHistorySeed: string;
    regimeSnapshots: string;
    researchSignals: string;
    researchEligibility: string;
    telemetry: string;
  };
  admin: {
    auth: string;
    overview: string;
    jobs: string;
    job: string;
    jobRetry: string;
    runs: string;
    schedule: string;
    audit: string;
    researchRuns: string;
    researchRun: string;
    researchRawSeries: string;
    researchSignal: string;
    researchRerun: string;
  };
};
